version: 2
jobs:
  test-bazel-28:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
    - run: sudo apt-get update && sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
    - run: wget -O /tmp/bazel-installer.sh https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel-0.28.1-installer-linux-x86_64.sh
    - run: chmod +x /tmp/bazel-installer.sh
    - run: /tmp/bazel-installer.sh --user
    - checkout
    - run: $HOME/bin/bazel test //...

  test-bazel-29:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
    - run: sudo apt-get update && sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
    - run: wget -O /tmp/bazel-installer.sh https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel-0.29.1-installer-linux-x86_64.sh
    - run: chmod +x /tmp/bazel-installer.sh
    - run: /tmp/bazel-installer.sh --user
    - checkout
    - run: $HOME/bin/bazel test //...

  test-bazel-1-0:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
    - run: sudo apt-get update && sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
    - run: wget -O /tmp/bazel-installer.sh https://github.com/bazelbuild/bazel/releases/download/1.0.0/bazel-1.0.0-installer-linux-x86_64.sh
    - run: chmod +x /tmp/bazel-installer.sh
    - run: /tmp/bazel-installer.sh --user
    - checkout
    - run: $HOME/bin/bazel test //...

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-bazel-28
      - test-bazel-29
      - test-bazel-1-0
